apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tusantos@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    http01: {}
